class AuthError(Exception):
    pass


class LinkError(Exception):
    pass
